using System;

class Program
{
    static void Main(string[] args)
    {
        
        // For Parts 1 user specified the number
        Console.Write("What is the magic number? ");
        int magicNumber1 = int.Parse(Console.ReadLine());
        Console.Write("What is your guess? ");
        int guess1 = int.Parse(Console.ReadLine());

        if (magicNumber1 > guess1)
            {
                Console.WriteLine("Higher");
            }
        else if (magicNumber1 < guess1)
            {
                Console.WriteLine("Lower");
            }
        else
            {
                Console.WriteLine("You guessed it!");
            }

        // For Parts 2 loop added that keeps looping as long as the guess does not match the magic number.
        int guess2 = -1;
        Console.Write("What is the magic number? ");
        int magicNumber2 = int.Parse(Console.ReadLine());
        while (guess2 != magicNumber2)
        {
            Console.Write("What is your guess? ");
            guess2 = int.Parse(Console.ReadLine());

            if (magicNumber2 > guess2)
                {
                    Console.WriteLine("Higher");
                }
            else if (magicNumber2 < guess2)
                {
                    Console.WriteLine("Lower");
                }
            else
                {
                    Console.WriteLine("You guessed it!");
                }
        }

        // For Part 3, the magic number generated by a random number
        string play_again = "yes"; 
        while (play_again == "yes") //for stretch challenge
        {
             Random randomGenerator = new Random();
             int magicNumber = randomGenerator.Next(1, 101);
             int guess = -1;
             int counter = 0; //Tracking counter to know how many guesses have been made.
            while (guess != magicNumber)
            {
                counter += 1;
                Console.Write($"{counter} try: What is your guess? ");
                guess = int.Parse(Console.ReadLine());
                if (magicNumber > guess)
                {
                    Console.WriteLine("Higher");
                }
                else if (magicNumber < guess)
                {
                    Console.WriteLine("Lower");
                }
                else
                {
                    Console.WriteLine("You guessed it!");
                    Console.WriteLine($"You did it in {counter} tries");//show how many guesses have been made.
                }
            }
            Console.Write("Do you want to play again? (write: yes or no) ");// "no" for exit of the loop
            play_again = Console.ReadLine();
        }
    }
}